typedef unsigned char uc;
typedef unsigned short us;
typedef unsigned int ui;

#define MAX_BUS 256
#define MAX_DEVICE 32
#define MAX_FUNCTIONS 8

#define COMMAND_PORT 0x0CF8
#define DATA_PORT 0x0CFC

#define BUS_SHIFT 16
#define DEVICE_SHIFT 11
#define FUNCTION_SHIFT 8
#define REGISTER_SHIFT 2
#define MULTIPLE_FUNCTIONS_SHIFT 7


#define DEVICEID_SHIFT 16
#define HEADER_TYPE_SHIFT 16
#define BIST_SHIFT 24
#define CLASS_CODE_SHIFT 8
#define BASE_CLASS_SHIFT 16
#define SUBCLASS_SHIFT 8
#define INTERRUPT_PIN_SHIFT 8
#define PRIMARY_BUS_NUMBER_SHIFT 0
#define SECONDARY_BUS_NUMBER_SHIFT 8
#define SUBORDINATE_BUS_NUMBER_SHIFT 16
#define IO_LIMIT_SHIFT 8
#define MEMORY_LIMIT_SHIFT 16
#define UPPER_LIMIT_SHIFT 16
#define SUBSYSTEMID_SHIFT 16
#define EXPANSION_ROM_BASE_ADDRESS_SHIFT 11
#define GNT_SHIFT 16
#define LAT_SHIFT 24
#define TYPE_BITS_SHIFT 1
#define MEMORY_SPACE_BAR_ADDRESS_SHIFT 4
#define IO_MEMORY_SPACE_BAR_ADDRESS_SHIFT 2

#define ID_REGISTER 0
#define STATUS_REGISTER 1
#define CLASS_CODE_REGISTER 2
#define CACHE_LINE_SIZE_REGISTER 3
#define HEADER_TYPE_REGISTER 3
#define BIST_REGISTER 3
#define FIRST_BAR_REGISTER 4
#define BUS_NUMBER_REGISTER 6
#define IO_DATA_REGISTER 7
#define MEMORY_DATA_REGISTER 8
#define PREF_MEMORY_DATA_REGISTER 9
#define UPPER_BASE_REGISTER 10
#define UPPER_LIMIT_REGISTER 11
#define UPPER_IO_REGISTER 12
#define CAPABILITIES_REGISTER 13
#define IS_POINTER_REGISTER 10
#define SUBSYSTEM_DATA_REGISTER 11
#define EXPANSION_ROM_BASE_ADDRESS_REGISTER 12
#define GNT_LAT_REGISTER 15
#define INTERRUPT_PIN_REGISTER 15
#define INTERRUPT_LINE_REGISTER 15

#define PREF_BAR 8

#define INTERRUPT_LINES_NUMBER 32
#define BAR_BRIDGE_QUANTITY 2
#define BAR_NBRIDGE_QUANTITY 6

#define PRIMARY_BUS_NUMBER "Primary bus number: %#x\n"
#define SECONDARY_BUS_NUMBER "Secondary bus number: %#x\n"
#define SUBORDINATE_BUS_NUMBER "Subordinate bus number: %#x\n"
#define NO_DEVICE 0xFFFFFFFF
